### ISSUE TITLE
Octopus is not working with "select" clause?

### ISSUE THREAD

**Issue by dkumar431** [thiagopradi/octopus#420]
Recently I have thought of using Octopus in my current application. Not sure but I am getting a lot of small issues. The below is very frustrating.

`Octopus.using(:slave1) do
       User.first
end` . 

This works fine and uses "slave1".
But not sure why the below is not working .

`Octopus.using(:slave1) do
       User.select("id")
end`

This one is not using slave1 but it fires on master database.

**Comment by jwilm** [comment]
@dkumar431 the second example does not work because it returns an AR Relation instead of a list of models. The relation is constructed in the block passed to using, but the models are not fetched until later.

**Comment by thiagopradi** [comment]
Hi @dkumar431 ,

@jwilm is correct - this is a limitation of the Gem. If you need a query to be executed on a specific slave, you need to force the query to complete inside it - otherwise, it will be sent to the master. I've added a spec to make sure the #select case inside a block is working: https://github.com/thiagopradi/octopus/commit/ed990724dc25da37cd8902f8320bab517bae9832.

I'm going to close this issue - feel free to send a PR to overcome this limitation.

Thiago
