### ISSUE TITLE
Octopus instantiate all migrations, that causes problems with Rails 5.1

### ISSUE THREAD

**Issue by stereosupersonic** [thiagopradi/octopus#430]
Rails 5.1 throws an exception when `ActiveRecord::Migration` is inherited directly.
https://github.com/rails/rails/commit/249f71a22ab21c03915da5606a063d321f04d4d3
normally this makes no problem with old migrations that don't follow this rule because Rails don't instantiate them when they are not running.

when Octopus is enabled, it will instantiate all migrations and raises an exception.

Is it possible that Octopus act like the active-record migrations and not instantiate all migrations?

**Comment by thiagopradi** [comment]
Hi @stereosupersonic,

Since Octopus needs to do some monkey-patch on migration methods, I don't think it's possible to not instantiate all migrations. What I recommend you is to either: 1) fix your migrations with a specific rails version; 2) move your legacy migrations to a separate folder.

Since we won't fix it, I'm going to close this issue.

Thiago
