### ISSUE TITLE
What should be in database.yml?

### ISSUE THREAD

**Issue by mahemoff** [thiagopradi/octopus#431]
New to Octopus, it looks like all databases need to be fully spec'd in shards.yml (I'm not using replication, ie the Rails app is only switching between different master databases). In that case, why is database.yml needed at all?

Emptying database.yml does lead to errors in startup though. ActiveSupport expects to see a key with same name as the environment. I think it could be changed by changing [DEFAULT_ENV](https://github.com/rails/rails/commit/bb1ecdcc677bf6e68e0252505509c089619b5b90#diff-193e6e4a86bf5d360a5001bce59334cb). Maybe the database specified in database.yml doesn't actually matter as Octopus will override it soon after Rails boots, but it feels dangerous not to keep it accurate, which means there's duplication between shards.yml and database.yml.

I'm mainly trying to understand exactly what should be in database.yml, assuming all databases are defined in shards.yml for each environment.

**Comment by coderhs** [comment]
>If Octopus finds the directive replicated: true, it will assume all shards as slaves, and the database specified in database.yml as master database. 

As mentioned in the wiki [on config file](https://github.com/thiagopradi/octopus/wiki/config-file)

**Comment by mahemoff** [comment]
They aren't slaves though. They are just separate databases.

**Comment by thiagopradi** [comment]
HI @mahemoff - having a database.yml file is not required by Octopus. You are seeing errors probably because of how ActiveRecord is integrated with Rails. However, Octopus's architecture relies on having a default ActiveRecord connection (which is called "master" internally). 

The "master" shard is the one that Octopus reverts a connection after executing a query. By doing so, every time that you execute a query and doesn't mention what shard it should be sent, it will be sent to master.

Let me know if this raises questions. I'm going to close this issue for now.

Thiago
