### ISSUE TITLE
Rails 6 release

### ISSUE THREAD

**Issue by brlo** [thiagopradi/octopus#539]
> Once the first version of Rails 6 beta is released, there will be a migration guide to help users migrate from Octopus to Rails 6.

https://weblog.rubyonrails.org/2019/8/18/this-week-in-rails-rails-6-is-released-sass-rails-6-improved-mysql2-error-and-more/

**Comment by thiagopradi** [comment]
@brlo - I haven't started writing the guide yet - will do it soon. I'll keep this issue open to track progress.

**Comment by one-more-alex** [comment]
Just an note.
Multi-database support there is poor...
Maybe it worth extend support on at least Rails 6.0.
For example, this bug https://github.com/rails/rails/issues/37837/

For myself I patched Octopus.rails52? to say "true" for Rails 6.0.
And it works so far except the place at ar-octopus-0.10.2/lib/octopus/model.rb in "def init_with(coder)".
Code coder['attributes']['current_shard'] raises exception because coder['attributes'] is null.
It have 'concise_attributes' instead.

But as for me, just need put there 
```ruby
return obj unless coder['attributes'].present?
```

My use of Octopus if very small (only for second independent connection to same database). So will hope it will work, till solution decision will be found.

**Comment by tibbon** [comment]
Very interested in a Rails 6 migration guide.

**Comment by sekiyama58** [comment]
Just for who are interested in ...

I am developing [the Octoball gem](https://github.com/aktsk/octoball) to make it easier to upgrade Octopus-based applications to Rails 6.1.
This gem provides Ocotpus-like sharding methods like `Model.using(:shard_name)` and shard tracking features, implemented on Rails 6.1 native multi-shard connection handling mechanism. Some of Octopus' features like round-robin scheduler of replicas are omitted for now.

Currently Rails 6.1 is still rc1, so I'm going to release this after the official release.
So far, it passes the specs derrived from Octopus with Rails6.1-rc1. Any tests, comments are welcome.

**Comment by thiagopradi** [comment]
Closing this issue in favor of https://github.com/thiagopradi/octopus/issues/532.

**Comment by rn-modi** [comment]
[> #532](https://github.com/thiagopradi/octopus/issues/539#issuecomment-534825735)

Any updates on the document @thiagopradi
